# You can write copyrights rules here. These rules will be copied into the outputs.

#
# Generated by erpcgen 1.10.0 on Wed May  6 18:30:16 2026.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for acc_gyroService
class acc_gyroServiceService(erpc.server.Service):
    def __init__(self, handler):
        super(acc_gyroServiceService, self).__init__(interface.Iacc_gyroService.SERVICE_ID)
        self._handler = handler
        self._methods = {
                interface.Iacc_gyroService.GETACCELEROMETER_ID: self._handle_GetAccelerometer,
                interface.Iacc_gyroService.GETGYRO_ID: self._handle_GetGyro,
            }

    def _handle_GetAccelerometer(self, sequence, codec):
        # Create reference objects to pass into handler for out/inout parameters.
        acce_x = erpc.Reference()
        acce_y = erpc.Reference()
        acce_z = erpc.Reference()

        # Read incoming parameters.

        # Invoke user implementation of remote function.
        self._handler.GetAccelerometer(acce_x, acce_y, acce_z)

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.Iacc_gyroService.SERVICE_ID,
            request=interface.Iacc_gyroService.GETACCELEROMETER_ID,
            sequence=sequence))
        if acce_x.value is None:
            raise ValueError("acce_x.value is None")
        codec.write_double(acce_x.value)
        if acce_y.value is None:
            raise ValueError("acce_y.value is None")
        codec.write_double(acce_y.value)
        if acce_z.value is None:
            raise ValueError("acce_z.value is None")
        codec.write_double(acce_z.value)

    def _handle_GetGyro(self, sequence, codec):
        # Create reference objects to pass into handler for out/inout parameters.
        gyro_x = erpc.Reference()
        gyro_y = erpc.Reference()
        gyro_z = erpc.Reference()

        # Read incoming parameters.

        # Invoke user implementation of remote function.
        self._handler.GetGyro(gyro_x, gyro_y, gyro_z)

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.Iacc_gyroService.SERVICE_ID,
            request=interface.Iacc_gyroService.GETGYRO_ID,
            sequence=sequence))
        if gyro_x.value is None:
            raise ValueError("gyro_x.value is None")
        codec.write_double(gyro_x.value)
        if gyro_y.value is None:
            raise ValueError("gyro_y.value is None")
        codec.write_double(gyro_y.value)
        if gyro_z.value is None:
            raise ValueError("gyro_z.value is None")
        codec.write_double(gyro_z.value)


