/*
 * You can write copyrights rules here. These rules will be copied into the outputs.
 */

/*
 * Generated by erpcgen 1.10.0 on Wed May  6 18:29:59 2026.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "acc_gyro_server.h"
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
#include <new>
#include "erpc_port.h"
#endif
#include "erpc_manually_constructed.hpp"

#if 11000 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

using namespace erpc;
using namespace std;

#if ERPC_NESTED_CALLS_DETECTION
extern bool nestingDetection;
#endif

ERPC_MANUALLY_CONSTRUCTED_STATIC(acc_gyroService_service, s_acc_gyroService_service);



// Call the correct server shim based on method unique ID.
erpc_status_t acc_gyroService_service::handleInvocation(uint32_t methodId, uint32_t sequence, Codec * codec, MessageBufferFactory *messageFactory)
{
    erpc_status_t erpcStatus;
    switch (methodId)
    {
        case kacc_gyroService_GetAccelerometer_id:
        {
            erpcStatus = GetAccelerometer_shim(codec, messageFactory, sequence);
            break;
        }

        case kacc_gyroService_GetGyro_id:
        {
            erpcStatus = GetGyro_shim(codec, messageFactory, sequence);
            break;
        }

        default:
        {
            erpcStatus = kErpcStatus_InvalidArgument;
            break;
        }
    }

    return erpcStatus;
}

// Server shim for GetAccelerometer of acc_gyroService interface.
erpc_status_t acc_gyroService_service::GetAccelerometer_shim(Codec * codec, MessageBufferFactory *messageFactory, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    double acce_x;
    double acce_y;
    double acce_z;

    // startReadMessage() was already called before this shim was invoked.

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        GetAccelerometer(&acce_x, &acce_y, &acce_z);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBuffer());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset();

        // Build response message.
        codec->startWriteMessage(kReplyMessage, kacc_gyroService_service_id, kacc_gyroService_GetAccelerometer_id, sequence);

        codec->write(acce_x);

        codec->write(acce_y);

        codec->write(acce_z);

        err = codec->getStatus();
    }

    return err;
}

// Server shim for GetGyro of acc_gyroService interface.
erpc_status_t acc_gyroService_service::GetGyro_shim(Codec * codec, MessageBufferFactory *messageFactory, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    double gyro_x;
    double gyro_y;
    double gyro_z;

    // startReadMessage() was already called before this shim was invoked.

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        GetGyro(&gyro_x, &gyro_y, &gyro_z);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBuffer());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset();

        // Build response message.
        codec->startWriteMessage(kReplyMessage, kacc_gyroService_service_id, kacc_gyroService_GetGyro_id, sequence);

        codec->write(gyro_x);

        codec->write(gyro_y);

        codec->write(gyro_z);

        err = codec->getStatus();
    }

    return err;
}

erpc_service_t create_acc_gyroService_service(void)
{
    erpc_service_t service;

#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    service = new (nothrow) acc_gyroService_service();
#else
    if (s_acc_gyroService_service.isUsed())
    {
        service = NULL;
    }
    else
    {
        s_acc_gyroService_service.construct();
        service = s_acc_gyroService_service.get();
    }
#endif

    return service;
}

void destroy_acc_gyroService_service(erpc_service_t service)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    erpc_assert(service != NULL);
    delete (acc_gyroService_service *)service;
#else
    (void)service;
    erpc_assert(service == s_acc_gyroService_service.get());
    s_acc_gyroService_service.destroy();
#endif
}

