# You can write copyrights rules here. These rules will be copied into the outputs.

#
# Generated by erpcgen 1.10.0 on Wed May  6 19:11:28 2026.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for LEDBlinkService
class ILEDBlinkService(object):
    SERVICE_ID = 1
    LED_ON_ID = 1
    LED_OFF_ID = 2
    READ_LED_ID = 3

    def led_on(self, led):
        raise NotImplementedError()

    def led_off(self, led):
        raise NotImplementedError()

    def read_led(self, led):
        raise NotImplementedError()


