/*
 * You can write copyrights rules here. These rules will be copied into the outputs.
 */

/*
 * Generated by erpcgen 1.10.0 on Wed May  6 18:29:59 2026.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_acc_gyro_server_h_)
#define _acc_gyro_server_h_

#ifdef __cplusplus
#include "erpc_server.hpp"
#include "erpc_codec.hpp"
extern "C"
{
#include "acc_gyro.h"
#include <stdint.h>
#include <stdbool.h>
}

#if 11000 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


/*!
 * @brief Service subclass for acc_gyroService.
 */
class acc_gyroService_service : public erpc::Service
{
public:
    acc_gyroService_service() : Service(kacc_gyroService_service_id) {}

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory);

private:
    /*! @brief Server shim for GetAccelerometer of acc_gyroService interface. */
    erpc_status_t GetAccelerometer_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for GetGyro of acc_gyroService interface. */
    erpc_status_t GetGyro_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);
};

extern "C" {
#else
#include "acc_gyro.h"
#endif // __cplusplus

typedef void * erpc_service_t;

/*! @brief Return acc_gyroService_service service object. */
erpc_service_t create_acc_gyroService_service(void);

/*! @brief Destroy acc_gyroService_service service object. */
void destroy_acc_gyroService_service(erpc_service_t service);

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // _acc_gyro_server_h_
