# You can write copyrights rules here. These rules will be copied into the outputs.

#
# Generated by erpcgen 1.10.0 on Wed May  6 18:30:16 2026.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for acc_gyroService
class Iacc_gyroService(object):
    SERVICE_ID = 1
    GETACCELEROMETER_ID = 1
    GETGYRO_ID = 2

    def GetAccelerometer(self, acce_x, acce_y, acce_z):
        raise NotImplementedError()

    def GetGyro(self, gyro_x, gyro_y, gyro_z):
        raise NotImplementedError()


