/*
 * You can write copyrights rules here. These rules will be copied into the outputs.
 */

/*
 * Generated by erpcgen 1.10.0 on Wed May  6 18:29:59 2026.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_acc_gyro_h_)
#define _acc_gyro_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 11000 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief acc_gyroService identifiers */
enum _acc_gyroService_ids
{
    kacc_gyroService_service_id = 1,
    kacc_gyroService_GetAccelerometer_id = 1,
    kacc_gyroService_GetGyro_id = 2,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name acc_gyroService
//@{
void GetAccelerometer(double * acce_x, double * acce_y, double * acce_z);

void GetGyro(double * gyro_x, double * gyro_y, double * gyro_z);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _acc_gyro_h_
