# You can write copyrights rules here. These rules will be copied into the outputs.

#
# Generated by erpcgen 1.10.0 on Wed May  6 18:30:16 2026.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for acc_gyroService
class acc_gyroServiceClient(interface.Iacc_gyroService):
    def __init__(self, manager):
        super(acc_gyroServiceClient, self).__init__()
        self._clientManager = manager

    def GetAccelerometer(self, acce_x, acce_y, acce_z):
        assert type(acce_x) is erpc.Reference, "out parameter must be a Reference object"
        assert type(acce_y) is erpc.Reference, "out parameter must be a Reference object"
        assert type(acce_z) is erpc.Reference, "out parameter must be a Reference object"

        # Build remote function invocation message.
        request = self._clientManager.create_request()
        codec = request.codec
        codec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.GETACCELEROMETER_ID,
                sequence=request.sequence))

        # Send request and process reply.
        self._clientManager.perform_request(request)
        acce_x.value = codec.read_double()
        acce_y.value = codec.read_double()
        acce_z.value = codec.read_double()

    def GetGyro(self, gyro_x, gyro_y, gyro_z):
        assert type(gyro_x) is erpc.Reference, "out parameter must be a Reference object"
        assert type(gyro_y) is erpc.Reference, "out parameter must be a Reference object"
        assert type(gyro_z) is erpc.Reference, "out parameter must be a Reference object"

        # Build remote function invocation message.
        request = self._clientManager.create_request()
        codec = request.codec
        codec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.GETGYRO_ID,
                sequence=request.sequence))

        # Send request and process reply.
        self._clientManager.perform_request(request)
        gyro_x.value = codec.read_double()
        gyro_y.value = codec.read_double()
        gyro_z.value = codec.read_double()


